extends: mergic
pull_request_rules:
  - name: Automatic queue
    conditions: []
    actions:
      queue:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
queue_rules:
  - name: default
    allow_queue_branch_edit: true
    batch_max_wait_time: 32 s
  - name: sqdqsd
  - name: defaultqsd
    allow_queue_branch_edit: true
    batch_max_wait_time: 32 s
priority_rules:
  - name: hotfix
    priority: high
    conditions:
      - base = main
  - name: low
    priority: low
    conditions:
      - base = main
  - name: critical
    priority: 5000
    conditions:
      - base = main
    allow_checks_interruption: false
