pull_request_rules:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
queue_rules:
  - allow_queue_branch_edit: false
    batch_max_wait_time: 30 s
    batch_size: 1
    queue_branch_merge_method: none
    queue_branch_prefix: mergify/merge-queue/
    speculative_checks: 1
